version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: Run the application
      #     command: node server.js
      #     background: true
      # - run:
      #     name: Run tests
      #     command: npm run test
      # The below two steps run in about the same time as the single 'node index.js' command
      # - run:
      #     name: Run ATT tests
      #     command: node tests/SRS-16a.js
      # - run:
      #     name: Run ATT tests
      #     command: node tests/SRS-777a.js
      # - run:
      #     name: Run ATT tests
      #     command: node index.js
      - run:
          name: Run tests
          command: circleci tests glob "tests/standalone/*.js" | circleci tests split